// Class automatically generated by Dev-C++ New Class wizard

#ifndef DATE_H
#define DATE_H

/*
 * No description
 */
class Date
{
	public:
		// class constructor
		Date();
		// class destructor
		~Date();
		static int printCount;
		void print() const;
};

#endif // DATE_H
