// Class automatically generated by Dev-C++ New Class wizard

#include "date.h" // class's header file

// class constructor
Date::Date()
{
	// insert your code here
}

// class destructor
Date::~Date()
{
	// insert your code here
}

void Date::print() {
     printCount++;
}
