// Class automatically generated by Dev-C++ New Class wizard

#include <cstdlib>
#ifndef SIMPLICE_H
#define SIMPLICE_H
#include <vector>


/*
 * No description
 */
class Simplice
{
      vector<int> localVertices;
      vector<int> localEdges;
      vector<int> localFaces;
      
	public:
		// class constructor
		Simplice();
		// class destructor
	    ~Simplice();
		void addVertex(int vertex){
          localVertices.push_back(vertex);
          }
		void addEdge(int edge){
          localEdges.push_back(edge);
          }
		void addFace(int face){
          localFaces.push_back(face);
          }
		vector<int>* getLocalVertices(){
             return &localVertices;
}
		vector<int>* getLocalEdges(){
             return &localEdges;
        }
		vector<int>* getLocalFace() {
             return &localFaces;
        }
	  
};

#endif // SIMPLICE_H
