// Class automatically generated by Dev-C++ New Class wizard

#include "triangulation.h" // class's header file
#include <cstdlib>
#include <map>
#include "triangulationmath.h"

map<int, Vertex> Triangulation::vertexTable;
map<int, Edge> Triangulation::edgeTable;
map<int, Face> Triangulation::faceTable;

// class constructor
Triangulation::Triangulation()
{
	// insert your code here
}

// class destructor
Triangulation::~Triangulation()
{
	// insert your code here
}

void Triangulation::putVertex(int key, Vertex v)
{
     (Triangulation::vertexTable).insert(pair<int, Vertex>(key, v));
}

void Triangulation::putEdge(int key, Edge v)
{
     (Triangulation::edgeTable).insert(pair<int, Edge>(key, v));
}

void Triangulation::putFace(int key, Face v)
{
     (Triangulation::faceTable).insert(pair<int, Face>(key, v));
}

double Triangulation::netCurvature()
{
       double net;
       map<int, Vertex>::iterator it;
       for(it = vertexTable.begin(); it != vertexTable.end(); it++)
       {
              net += curvature((*it).second);
       }
       return net;
}
