#define IDC_STATIC -1
#define IDR_MAINMENU    101
#define IDD_MAIN        102
#define IDD_CHOOSEFILETYPE 103
#define IDD_FLOWDIALOG     104
#define IDD_POLYGON        105
#define ID_FILE_EXIT                    40001
#define ID_FILE_LOAD_MANIFOLD           40002
#define ID_FILE_LOAD_PLANE              40003
#define ID_FILE_SAVE_TRIANGULATION      40004
#define ID_FILE_SAVE_FLOW               40005
#define ID_FILE_SAVE_PLANE              40006
#define ID_RUN_FLOW_EUCLIDEAN           40007
#define ID_RUN_FLOW_SPHERICAL           40008
#define ID_RUN_FLOW_HYPERBOLIC          40009
#define ID_RUN_FLIPALGORITHM            40010
#define ID_RUN_WEIGHTEDFLIPALGORITHM    40011
#define ID_FILE_LOAD_3DMANIFOLD         40012
#define ID_RUN_FLOW_YAMABE              40013
#define IDC_CONSOLE                     1001
#define IDC_RESULTSBUTTON               1002
#define IDC_RESULTSFIELD                1003
#define IDC_FORMATSELECTBOX             1004
#define IDC_STEPSTEXT                   1005
#define IDC_DTTEXT                      1006
#define IDC_WEIGHTSELECTBOX             1007
#define IDC_RESULTSSELECTBOX            1008
#define IDC_FLOWSELECTBOX               1009
#define IDC_HIDDENTEXT                  1010
#define IDC_POLYGON                     1011
#define IDSTANDARD                      5001
#define IDLUTZ                          5002
#define IDPRINTSTEP                     5003
#define IDPRINTVERTEX                   5004
#define IDPRINTNUM                      5005
#define IDWEIGHTSRANDOM                 5006
#define IDWEIGHTSFILE                   5007
#define IDPRINTNUMSTEP                  5008
#define IDPOLYGON                       5009
