// Class automatically generated by Dev-C++ New Class wizard

#include "simplice.h"
#include <vector>
#include <cstdlib>

Simplice::Simplice()
{
	
}

// class destructor
Simplice::~Simplice()
{
	// insert your code here
}

